### PR TITLE
Viewport2DIn3D

### PR DESCRIPTION
**Pull request by sean-delcastillo**
# Implementing Reusable Viewport2DIn3D Scene
An implementation of having a viewport render a 2D UI in 3D inspired by the Godot XR Tools project's `viewport_2d_in_3d` implementation. The main guts of this already exited in the Killhouse demo scene for the screen that lets you change your dominant hand. I mainly focused on generalizing this implementation for reuse. This implementation should behave near identically (if not totally identically) to what is found in the Killhouse demo scene.

## Implementation
Viewport2DIn3D is a Node3D derived node that needs a PlaneMesh child to act as a screen that is managed by the script to render the SubViewport which contains a Control scene for 2D UI. 

### Screen Properties
This node is highly based on the implementation in the Godot XR Tool project. The main difference is that this node does not completely manage the screen mesh and so does not need to track many mesh render properties. However this means that it must make sure that the collision shape is kept updated with the mesh. This is done using the `CheckScreenProperties` method. 

https://github.com/VirtualNubs/NXR/blob/9e721ccbc1b5ee8e7676b38afe6973f4614f30da/addons/nxr/scripts/ui/Viewport2DIn3D.cs#L264-L272

### Update Loop
Keeping the screen mesh updated with the Subviewport is handled by the two update methods, `Update` and `UpdateRender` where `Update` calls `UpdateRender` along with also checking if the collision size needs to be changed to keep in sync with the screen size. All updates are handled via bit flags in the `_dirty` bitfield. 

https://github.com/VirtualNubs/NXR/blob/9e721ccbc1b5ee8e7676b38afe6973f4614f30da/addons/nxr/scripts/ui/Viewport2DIn3D.cs#L190-L199

For example this check in the `UpdateRender` method updates the screen material and updates the albedo and surface to ensure that the material is reapplied.

https://github.com/VirtualNubs/NXR/blob/9e721ccbc1b5ee8e7676b38afe6973f4614f30da/addons/nxr/scripts/ui/Viewport2DIn3D.cs#L202-L219

This check updates the scene by managing the SubViewport child and triggering a redraw. 

These flags are controlled when their backing store is set

https://github.com/VirtualNubs/NXR/blob/9e721ccbc1b5ee8e7676b38afe6973f4614f30da/addons/nxr/scripts/ui/Viewport2DIn3D.cs#L15-L28

## Modifying Pointer.cs
To make use of the already existing code for this functionality I changed the code in the `TrySendInputToGUI` method to grab the SubViewport node in the new scene structure.

https://github.com/VirtualNubs/NXR/blob/2e044cc12fc64e1da035eee5c1fc36af3af74b3b/addons/nxr/scripts/ui/Pointer.cs#L69-L89

The Pointer will collide with the collision child of the Viewport2DIn3D node so we will need to check if the collider's parent is a Viewport2Din3D node from which we can access the Subviewport.

# Class Documentation
When writing this feature I added XML documentation comments as specified by the [C# Language Specification, Annex D ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments). I wanted to start setting a standard of documentation for new code (and a future revision of current code) to include documentation comments. I believe that this will help both addon users and future project contributors gain an understanding of the codebase and how to leverage it for their purposes.

The Viewport2DIn3D class contains documentation strings for the class itself, all class members part of the public API, and certain private members I thought should be explained as they are large, important parts of the class's function. 

Documenting at least the class's public API would help immensely with code comprehension moving forward and using XML documentation comments is well supported by C# as part of its specifications and in tools such as Visual Studio through [generating and inserting XML comment templates](https://learn.microsoft.com/en-us/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2022).

### CODE REVIEW

**Comment by sean-delcastillo** [comment]
I think the same-line exports are very clean looking, especially in ExportGroups like your linked example. I wanted to bring up enforcing a style guide for the project; it'll help keep diffs for file changes lean to make reviewing pull requests cleaner. I'll make an issue so we can track our solutions past this PR.

As for this PR I apologize for holding it up for so long. I've gotten busy with some stuff, but I'm aiming to work on it and mark this ready for review ASAP!

**Comment by sean-delcastillo** [comment]
> I'll make an issue so we can track our solutions past this PR.

The style guide issue is #19

**Comment by sean-delcastillo** [comment]
Fixed an issue with having multiple Viewport2Din3Ds scene instances in one scene, added controls for the child SubViewport, and added more public member documentation. Should be ready for review now.

**Comment by stumpynub** [comment]
Just had a chance to try it out. Works great! The only issue I saw was the shooting range demo UI needing to be updated, but everything was flawless!

**Comment by stumpynub** [comment]
Found another thing while testing. When having UI elements off center it seems like the pointer coordinates are flipped. Looks like a mistake in Pointer.cs with a negative axis.  

https://github.com/VirtualNubs/NXR/blob/310092937faf61a5b996ef7ed9d030be973bc169/addons/nxr/scripts/ui/Pointer.cs#L76

**Pull request merged**
